### ISSUE TITLE
TypeError: Expected 'Iterator' as the return annotation for `__iter__` of ExperienceSourceDataset, but found typing.Iterable Hi, i'm using tpus and i have also tried gpus. but this error still persists. and yes i'm using the newest version. 

### ISSUE THREAD

**Issue by jordanvalter** [tgisaturday/dalle-lightning#12]
WARNING:root:Waiting for TPU to be start up with version pytorch-1.9...
WARNING:root:Waiting for TPU to be start up with version pytorch-1.9...
WARNING:root:TPU has started up successfully with version pytorch-1.9
Traceback (most recent call last):
  File "/content/lib/dalle-lightning/train_vae.py", line 17, in <module>
    from pl_dalle.callbacks import ReconstructedImageLogger
  File "/content/lib/dalle-lightning/pl_dalle/callbacks.py", line 8, in <module>
    from pl_bolts.utils import _TORCHVISION_AVAILABLE
  File "/usr/local/lib/python3.7/dist-packages/pl_bolts/__init__.py", line 19, in <module>
    from pl_bolts import (  # noqa: E402
  File "/usr/local/lib/python3.7/dist-packages/pl_bolts/datamodules/__init__.py", line 5, in <module>
    from pl_bolts.datamodules.experience_source import DiscountedExperienceSource, ExperienceSource, ExperienceSourceDataset
  File "/usr/local/lib/python3.7/dist-packages/pl_bolts/datamodules/experience_source.py", line 24, in <module>
    class ExperienceSourceDataset(IterableDataset):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_typing.py", line 273, in __new__
    return super().__new__(cls, name, bases, namespace, **kwargs)  # type: ignore[call-overload]
  File "/usr/lib/python3.7/abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_typing.py", line 371, in _dp_init_subclass
    ", but found {}".format(sub_cls.__name__, _type_repr(hints['return'])))
TypeError: Expected 'Iterator' as the return annotation for `__iter__` of ExperienceSourceDataset, but found typing.Iterable

**Comment by matteopilotto** [comment]
Hi @jordanvalter,
assuming you're running the colab notebook, adding this line of code to the setup will solve the problem:
`!pip install git+https://github.com/PytorchLightning/lightning-bolts.git@master --upgrade`

**Comment by jordanvalter** [comment]
That seems to have worked thanks! closing now.

**Comment by tgisaturday** [comment]
> Hi @jordanvalter,
> assuming you're running the colab notebook, adding this line of code to the setup will solve the problem:
> `!pip install git+https://github.com/PytorchLightning/lightning-bolts.git@master --upgrade`

I'll update requirements.txt also. Thank you. I've been only installing pytorch-lightning from source but bolts also seems to suffer same problem.

**Comment by tgisaturday** [comment]
@jordanvalter @afiaka87 just removed pl_bolts dependency completely.

**Comment by GuangfuWang** [comment]
> Hi @jordanvalter, assuming you're running the colab notebook, adding this line of code to the setup will solve the problem: `!pip install git+https://github.com/PytorchLightning/lightning-bolts.git@master --upgrade`

any clues for vscode && gpu installed in my own computer? huge thx!!

**Comment by ShamimAlMahmud** [comment]
`!pip install git+https://github.com/PytorchLightning/lightning-bolts.git@master --upgrade` Thank you.
