### ISSUE TITLE
vqgan working now (except there's a small bug)

### ISSUE THREAD

**Issue by afiaka87** [tgisaturday/dalle-lightning#13]
Great work with writing out the pl_bolts requirement. So far I can at least confirm that the VAE training works now on GPU in colab. At least, for `vqgan`. 

For some reason the `args.gpus` flag isn't quite making it to the Trainer? Couldn't quite figure out what was wrong and I'm a bit scattered at the moment. 

Anyway; small benefit of that is that I tested it on CPU accident which works as well.

**Comment by tgisaturday** [comment]
@afiaka87 Maybe..did you set --use_tpus flag on? It automatically sets gpus = None. https://github.com/tgisaturday/dalle-lightning/blob/f41529c3c27399e3415f504cf93983bc6dfb3c62/train_vae.py#L193

**Comment by afiaka87** [comment]
Hm it seems this is working now.
