### ISSUE TITLE
VQGAN callback breaks

### ISSUE THREAD

**Issue by afiaka87** [tgisaturday/dalle-lightning#14]
Getting an error when training `vqgan`

https://github.com/tgisaturday/dalle-lightning/blob/b4164106fee0d25ad0312ff1cbc24516c78b905d/pl_dalle/callbacks.py#L70

Modifying to grab the first element beforehand fixes the issue.
```python
    ) -> None:
        """Called when the train batch ends."""
        if trainer.global_step % self.every_n_steps == 0:
            # x = outputs['x']
            x = outputs[0]['x']
            xrec = outputs[0]['xrec']
```

**Comment by tgisaturday** [comment]
@afiaka87 Seems like this is vqgan specific error because of two optimizer. I'll try to figure out how to handle this properly.

**Comment by tgisaturday** [comment]
@afiaka87 fixed in this [commit](https://github.com/tgisaturday/dalle-lightning/commit/2b5af81a35637009ad82159cd8da0806de7687f1)
