### ISSUE TITLE
DALL-E training code (often) gets stuck indefinitely after completing validation

### ISSUE THREAD

**Issue by matteopilotto** [tgisaturday/dalle-lightning#15]
Hi @tgisaturday and @afiaka87,
I've been working with your repo for a while and overall I didn't have many problems. However, from last week I started noticing that often the code for training DALLE doesn't exit the process after completing training and validation. In other words, it gets stuck indefinitely in that state and two weeks ago I've never encountered this behavior.

This is a screenshot when the code just works fine:
![image](https://user-images.githubusercontent.com/79744680/128674629-05533e8f-364b-4d20-95d9-d82051a7bbe9.png)

This is when the code gets stuck:
![image](https://user-images.githubusercontent.com/79744680/128674718-2849238c-06e7-4461-a0b7-4c3802ca14ed.png)

Usually I tried to solve issues by myself, but this time without a error message I have no idea where to start. The only thing I can do now is to restart the colab session and rerun the cells once again because the checkpoint is not saved. Since the issue is quite annoying because it forces me to train the model one epoch at time to minimize waste of time in case the problem shows up, it would be great if you could give me any idea on how I might solve it.

Thank you both for your help.

**Comment by tgisaturday** [comment]
@matteopilotto First of all, thank you for your interest. I'm also facing various sudden shutdown, hanging, deadlock etc. If you are using TPUs, this can be TPU internal error, which are consuming most of my time these days. Especially with dalle training, there seems to be lots of optimization issue and this can be solved by refactoring the whole dalle model. I'm about to finish debugging and refactoring VAEs and also working on dataloader issues. After that I'm going to work on dalle refactoring. As always, any PRs for better repo is always welcome.

**Comment by tgisaturday** [comment]
In this case, please try out VAE training. There won't be as much errors or unexpected behaviors compared to dalle training.

**Comment by matteopilotto** [comment]
Honestly, I haven't experience so many problems. The code is very neat and clean. The very few errors I encountered could be fixed with simple adjustments, like the pytorch.bolts error that could be solved with that single line of code. And I am not an expert of any kind. The stuff you're doing here is absolutely mind blowing for me.
I just wonder why until two weeks ago, I've never had such issue... anyway, I will take a closer look to the code and if I find something useful, I'll be extremely happy to make my contribution.
Thanks for the support!

**Comment by tgisaturday** [comment]
@matteopilotto I thought you were using GPUs but it seems like you are using TPUs. If this is the case, try setting num_worker to 16~48. 
Yes, something happened in TPU side around two weeks and I was having similar problem in https://github.com/tgisaturday/dalle-lightning/issues/11.

**Comment by tgisaturday** [comment]
> Hi @tgisaturday and @afiaka87,
> I've been working with your repo for a while and overall I didn't have many problems. However, from last week I started noticing that often the code for training DALLE doesn't exit the process after completing training and validation. In other words, it gets stuck indefinitely in that state and two weeks ago I've never encountered this behavior.
> 
> This is a screenshot when the code just works fine:
> ![image](https://user-images.githubusercontent.com/79744680/128674629-05533e8f-364b-4d20-95d9-d82051a7bbe9.png)
> 
> This is when the code gets stuck:
> ![image](https://user-images.githubusercontent.com/79744680/128674718-2849238c-06e7-4461-a0b7-4c3802ca14ed.png)
> 
> Usually I tried to solve issues by myself, but this time without a error message I have no idea where to start. The only thing I can do now is to restart the colab session and rerun the cells once again because the checkpoint is not saved. Since the issue is quite annoying because it forces me to train the model one epoch at time to minimize waste of time in case the problem shows up, it would be great if you could give me any idea on how I might solve it.
> 
> Thank you both for your help.

@matteopilotto regarding checkpoint saving, try --backup flag. It saves temporary checkpoint for backup and resume for every 1000 steps. You can change the frequency with num_backup_steps. This is really helpful when using TPUs because sudden TPU stop happens quite often.

**Comment by matteopilotto** [comment]
@tgisaturday yeah, I'm running TPU on colab... my bad, I kind of given it for granted.
I tried your idea of increasing the number of workers, but in my case unfortunately it didn't work. I tested the code several times with different numbers, but I could fine any consistency: sometimes it works and sometime it hangs.
Might this related to the fact that I'm running on colab?
On the contrary, I tried the idea of setting the workers to 0, mentioned in the other issue, and in this case it seems to work. The training is way slower, but at least I don't have to constantly check the code.
I'll keep you updated and thanks for the support.

**Comment by tgisaturday** [comment]
@matteopilotto I'm right now testing train_dalle on gpus and encountering some unexpected and never seen errors. This can be a cause. I'll fix them and try again on TPUs and GPUs.

**Comment by tgisaturday** [comment]
> @matteopilotto I'm right now testing train_dalle on gpus and encountering some unexpected and never seen errors. This can be a cause. I'll fix them and try again on TPUs and GPUs.

Haven't tested on TPUs yet but solved all (maybe most of) the bugs of dalle training. I've checked that train_dalle.py is now working on GPUs with DDP setting.

**Comment by matteopilotto** [comment]
> 
> 
> > @matteopilotto I'm right now testing train_dalle on gpus and encountering some unexpected and never seen errors. This can be a cause. I'll fix them and try again on TPUs and GPUs.
> 
> Haven't tested on TPUs yet but solved all (maybe most of) the bugs of dalle training. I've checked that train_dalle.py is now working on GPUs with DDP setting.

I tested the code multiple times with the new changes and different number of workers (4, 8, 16, 24, 32), but at least for the TPU part I didn't notice any change regarding the hanging issue.
Anyway, thanks for keeping me update.

**Comment by tgisaturday** [comment]
@matteopilotto @harubaru I think I figured out the root cause. Try newest update for the workaround.

**Comment by matteopilotto** [comment]
Hey @tgisaturday,
Sorry if I didn't reply immediately, but I took a few days to test the code. And yeah, with the last update it seems that the training doesn't hang anymore. Conversely, I've noticed that now the code uses a lot of RAM: with only 2 workers it already requires more than 18GB of RAM and with 16 workers the session crashes.
Fortunately, I have a colab pro subscription, but I guess that for free users that might be a problem. And maybe be it's supposed to be like that, but I thought it was better to let you know.

Besides, I'm super curious to know what/where was the problem and how you fixed it.
As always, thanks for the support!

EDIT:
I forgot to mention that now during training I get the following warning, even though everything works just fine:
```
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/data_loading.py:111: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 40 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/data_loading.py:111: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 40 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."
```

**Comment by tgisaturday** [comment]
@matteopilotto Thank you for testing out on colab. I made a workaround by modifying pytorch-lightning. Lightning uses 'fork' as a spawn method while all the official torch-xla codes use 'spawn'. While 'fork' should not cause any problem theoratically, it is causing many unexpected behaviours right now, especially with large TPU pods. Main difference between 'fork' and 'spawn' is that 'spawn' copies everything (including dataloader) when creating child while 'fork' copies only required classes. For this reason, I've also found that num_worker should be set to 0 when using 'spawn'

**Comment by tgisaturday** [comment]
I've seen previous issues on torch-xla that 'spawn' is not working on colab but seems like they have already fixed it. Since the workaround is still unstable, I'm keeping it as a forked version of pytorch-lightning : https://github.com/tgisaturday/pytorch-lightning/blob/master/pytorch_lightning/plugins/training_type/tpu_spawn.py
