### ISSUE TITLE
VQGAN training breaks on GPU

### ISSUE THREAD

**Issue by afiaka87** [tgisaturday/dalle-lightning#6]
```sh
  File "/content/lib/dalle-lightning/pl_dalle/modules/vqvae/quantize.py", line 20, in forward
    z_flattened = z.view(-1, self.embedding_dim)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

Works fine on TPU, breaks on GPU. Will `reshape` work on TPU?

**Comment by tgisaturday** [comment]
I've forgot to add .contiguous() after permute. It's might work right now. Thanks for letting me know :)

**Comment by afiaka87** [comment]
I'll try it out on GPU colab later today.

**Comment by tgisaturday** [comment]
@afiaka87 One more suggestion. I've been also testing vqgan on GPU and loss goes nan with precision = 16. Try with --precision 32 first.
