### ISSUE TITLE
Using real data breaks training

### ISSUE THREAD

**Issue by afiaka87** [tgisaturday/dalle-lightning#7]
Whoops! Looks like there needs to be a call to train_transform/val_transform here instead of the non-existent `transform`

https://github.com/tgisaturday/dalle-lightning/blob/f995ecabc2b17c5826719f4db2dc79befbc6aaa8/pl_dalle/loader.py#L94

**Comment by tgisaturday** [comment]
Fixed. There were more typos regarding self.transform :(
